name: doubleeaglebbq
recipe: wordpress
# env_file:
#   - .env.example
#   - .env
excludes:
  - vendor
  - wp-content/themes/double-eagle/vendor
  - wp-content/themes/double-eagle/node_modules
config:
  php: "7.4"
  via: nginx
  database: mariadb
  cache: redis
  xdebug: false
  webroot: web
services:
  appserver:
    overrides:
      # See: https://github.com/docker/for-linux/issues/264#issuecomment-763555307
      extra_hosts:
        - "host.docker.internal:host-gateway"
      environment:
        PHP_IDE_CONFIG: "${PHP_IDE_CONFIG:-serverName=appserver}"
        XDEBUG_MODE: "${XDEBUG_MODE:-develop,debug}"
        XDEBUG_CONFIG: "${XDEBUG_CONFIG:-client_host=host.docker.internal discover_client_host=true}"
        WP_REDIS_HOST: cache
    build:
      - composer install --working-dir=/app --no-progress --no-interaction --no-progress --no-scripts
      - composer install --working-dir=/app/wp-content/themes/double-eagle --no-progress --no-interaction --no-progress --no-scripts
  theme:
    type: node:12
    ssl: true
    build:
      - cd /app/wp-content/themes/double-eagle && npm i
      - cd /app/wp-content/themes/double-eagle && npm run-script build
    scanner: false
  sendmailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
  database:
    type: mariadb
    portforward: true
  cache:
    type: redis:4
    portforward: true
tooling:
  redis-cli:
    service: cache
  theme:
    service: theme
    description: Runs npm commands within the theme directory
    cmd: timeout --preserve-status -k 360 300 /usr/local/bin/npm
    dir: /app/wp-content/themes/double-eagle
  flush:
    service: appserver
    description: Flush all caches
    cmd:
      - rm -rf wp-content/uploads/cache/*
      - appserver: wp rewrite flush
      - appserver: wp cache flush
      - cache: redis-cli FLUSHDB
  sync:
    service: appserver
    description: Syncs uploads and other folders with the production server
    cmd: wp sync
    options:
      env:
        passthrough: true
        alias:
          - e
        default: live
        describe: Sync from specified environment
  reset-db:
    service: appserver
    description: Resets database to latest data from production
    cmd:
      - wp db reset --yes
      - wp @live db export - | wp db import -
      - wp plugin activate rewrite-testing query-monitor
  reset-deps:
    service: appserver
    cmd:
      - rm -rf /app/web/wp /app/vendor
      - rm -rf /app/wp-content/themes/double-eagle/node_modules /app/wp-content/themes/double-eagle/dist/* /app/wp-content/themes/double-eagle/vendor
      - appserver: composer install --working-dir=/app --no-progress --no-interaction --no-progress --no-scripts
      - appserver: composer install --working-dir=/app/wp-content/themes/double-eagle --no-progress --no-interaction --no-progress --no-scripts
      - theme: npm --prefix /app/wp-content/themes/double-eagle ci
      - theme: npm --prefix /app/wp-content/themes/double-eagle run-script build
  login:
    service: appserver
    description: Generate administrator login URL
    cmd:
      - wp package path aaemnnosttv/wp-cli-login-command >/dev/null 2>&1 || wp package install aaemnnosttv/wp-cli-login-command
      - wp plugin is-active wp-cli-login-server || wp login install --activate --yes
      - wp login as 1
  migrate:
    service: appserver
    description: Run migration scripts
    cmd:
      - /app/database/migrations/migrate-posts.sh
      - /app/database/migrations/migrate-resources.sh
events:
  post-start:
    - database: sleep 5 # give db time to boot
    - appserver: >-
        if ! $(wp core is-installed); then
          wp @live db export - | wp db import -;
        fi;
        wp plugin activate rewrite-testing query-monitor;
        wp spinupwp update-object-cache-dropin;
    - appserver: which php && php --version
    - appserver: which wp && wp cli version
    - appserver: which composer && composer --version
    - theme: which node && node --version
    - theme: which npm && npm --version
    - theme: which yarn && yarn --version
    - appserver: which wp && wp core version
